### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by JiangWeixian** [spring-catponents/templates#268]
3.x is a big breaking change of `@aiou/neo`

Here are features that current development focused on:

- [ ] support install `preset-xx`, `preset-xx` is collection of templates
- [ ] support add `git+xxx` packages
- [ ] cache created template like `pnpm`, will be able to create repo offline
